// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web; 
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC02JY2sAvL2sVDzc2BaO-I-NKWsEwEW60',
    appId: '1:387798170244:web:a4f7672a3d0dbf6af260d1',
    messagingSenderId: '387798170244',
    projectId: 'foodwastezero-528ac',
    authDomain: 'foodwastezero-528ac.firebaseapp.com',
    storageBucket: 'foodwastezero-528ac.firebasestorage.app',
    measurementId: 'G-EJT8VV2Y4N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDbUhX4RtdfZCWTF-Bq5wgm9nLgJ5ds48',
    appId: '1:387798170244:android:08eb0c73ba3edb89f260d1',
    messagingSenderId: '387798170244',
    projectId: 'foodwastezero-528ac',
    storageBucket: 'foodwastezero-528ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOON0GkHtpfB840UPbKrL7crddgR8tsc4',
    appId: '1:387798170244:ios:5a295dbee0d7cc54f260d1',
    messagingSenderId: '387798170244',
    projectId: 'foodwastezero-528ac',
    storageBucket: 'foodwastezero-528ac.firebasestorage.app',
    iosBundleId: 'com.example.praktikum2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOON0GkHtpfB840UPbKrL7crddgR8tsc4',
    appId: '1:387798170244:ios:5a295dbee0d7cc54f260d1',
    messagingSenderId: '387798170244',
    projectId: 'foodwastezero-528ac',
    storageBucket: 'foodwastezero-528ac.firebasestorage.app',
    iosBundleId: 'com.example.praktikum2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC02JY2sAvL2sVDzc2BaO-I-NKWsEwEW60',
    appId: '1:387798170244:web:8b695b77bf54b85bf260d1',
    messagingSenderId: '387798170244',
    projectId: 'foodwastezero-528ac',
    authDomain: 'foodwastezero-528ac.firebaseapp.com',
    storageBucket: 'foodwastezero-528ac.firebasestorage.app',
    measurementId: 'G-XD5XL9HQW9',
  );
}
